version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo Installing Composer dependencies...
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-interaction --prefer-dist --optimize-autoloader
  pre_build:
    commands:
      - echo Copying .env...
      - cp .env.example .env
      - php artisan key:generate
  build:
    commands:
      - echo Running migrations...
      - php artisan migrate --force
      - echo Build completed.
artifacts:
  files:
    - '**/*'
  discard-paths: no